version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    network_mode: host
    environment:
      MONGO_DB_CONNECTION_URL: ${MONGO_DB_CONNECTION_URL}

  mongodb:
    image: mongo:8.0.1
    container_name: ct-pod-mongo
    network_mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_learn:/data/db

volumes:
  mongodb_learn:
